name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  doxygen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build docs
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'doxygen.conf'

    - name: OpenAPI Generator Action
      uses: kpurdon/openapi-generator-action@v0.0.3
      with:
        args: "generate -i swagger.yaml -g html -o docs/rest --additional-properties=infoEmail=kytka.honza@gmail.com,infoUrl=https://muph0.github.io/iot-dash-backend/,licenseInfo=,licenseUrl="

    - name: Transfer docs to runner
      run: sudo chown -R runner docs

    - name: Copy static files
      run: mv docs/rest/index.html docs/rest.html ;
           cp -ru docs/*.png docs/*.svg docs/*.html docs/html/ ;
           cp swagger.yaml docs/html/ ;

    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: pages
        folder: docs/html